version: "1"

template_engine:
  engine: "mottainai"

include_profiles_files:
- ../common/profiles/net-mottainai0.yml
- ../common/profiles/default.yml
- ../common/profiles/loop.yml
- ../common/profiles/privileged.yml
- ../common/profiles/zfs.yml
- ../common/profiles/docker.yml

include_networks_files:
- ../common/networks/mottainai0.yml

commands:

  - name: build-repo-with-docker
    project: "devs::build-repo"
    apply_alias: true
    description: |
      Clone and build passed repository.
      Use this if Docker service is needed.

      lxd-compose c r devs::build-repo build-repo \
        --env "REPO=https://github.com/MottainaiCI/lxd-compose.git" \
        --env "BUILD_CMD=make build" \
        --env "TEST_CMD=make tests" \

    enable_flags:
      - setup
      - setup_docker
      - build
      - test

  - name: build-repo
    description: |
      Clone, build and test passed repository.

      lxd-compose c r devs::build-repo build-repo \
        --env "REPO=https://github.com/MottainaiCI/lxd-compose.git" \
        --env "BUILD_CMD=make build" \
        --env "TEST_CMD=make tests" \


    project: "devs::build-repo"
    apply_alias: true

  - name: build-without-tests
    project: "devs::build-repo"
    apply_alias: true
    description: |
      Clone and build passed repository.

      lxd-compose c r dev::build-repo build-repo \
        --env "REPO=https://github.com/MottainaiCI/lxd-compose.git" \
        --env "BUILD_CMD=make build"

    disable_flags:
      - test

projects:

  - name: "devs::build-repo"
    description: |
      An integration project to build a repository and run test

    vars:
      - envs:
          REPO: https://github.com/MottainaiCI/lxd-compose.git
          BRANCH: master
          PACKAGES_SETUP: "wget jq docker.io bridge-utils make curl golang"
          yq_version: "3.4.1"
          GOPATH: "/go"

    groups:
      - name: "devs::build-repo"
        description: "Build group node"

        connection: "{{ .Values.connection }}"
        common_profiles:
          - default
          - net-mottainai0

        ephemeral: true

        nodes:
          - name: dev-repo-build
            image_source: "{{ .Values.default_ubuntu_image }}"
            image_remote_server: "images"

            entrypoint:
              - "/bin/bash"
              - "-c"

            profiles:
              - docker
              - privileged

            hooks:
              - event: post-node-creation
                flags:
                  - setup
                commands:
                  - sleep 5
                  - apt-get update
                  - apt-get upgrade -y
                  - apt-get install -y ${PACKAGES_SETUP}
                  - |
                    wget -q -O /usr/bin/yq \
                    https://github.com/mikefarah/yq/releases/download/${yq_version}/yq_linux_amd64
                  - chmod a+x /usr/bin/yq

              - event: post-node-sync
                disable: true
                flags:
                  - setup_docker
                commands:
                  - systemctl daemon-reload
                  - systemctl start docker

              - event: post-node-sync
                flags:
                  - build
                commands:
                  - eval 'rm -rf /build || true'
                  - git clone ${REPO} -b ${BRANCH} /build
                  - >-
                    export PATH=$PATH:$GOPATH/bin ;
                    if [ -z "${BUILD_CMD}" ] ; then BUILD_CMD="make build" ; fi ;
                    cd /build && ${BUILD_CMD}

              - event: post-node-sync
                flags:
                  - test
                commands:
                  - >-
                    export PATH=$PATH:$GOPATH/bin ;
                    if [ -z "${TEST_CMD}" ] ; then TEST_CMD="make tests" ; fi ;
                    cd /build && ${TEST_CMD}
