default-remote: local
remotes:
  images:
    addr: https://images.linuxcontainers.org
    protocol: simplestreams
    public: true
  keybase-geaaru:
    addr: https://geaaru.keybase.pub/lxd-images
    protocol: simplestreams
    public: true
  macaroni:
    addr: https://macaronios.mirror.garr.it/images/lxd-images
    protocol: simplestreams
    public: true
  local:
    addr: unix://
    public: false
  local-snapd:
    addr: unix:///var/snap/lxd/common/lxd/unix.socket
    public: false
aliases: {}
