default-remote: local
remotes:
  images:
    addr: https://images.linuxcontainers.org
    protocol: simplestreams
    public: true
  keybase-geaaru:
    addr: https://geaaru.keybase.pub/lxd-images
    protocol: simplestreams
    public: true
  local:
    addr: unix://
    public: false
  nevyl:
    addr: https://192.168.0.91:8443
    auth_type: tls
    project: default
    protocol: lxd
    public: false
aliases: {}
