
#-------------------------------------------#
# Oracle Database project customization
#-------------------------------------------#
oracledb:
  # Enable/Disable storage mount from host.
  enable_storage_from_host: false

  # Path of the host to mount in the container.
  host_data_path: /data/CONTAINER_STORAGE/oracle_container

#-------------------------------------------#
# Mottainai Service project customization
#-------------------------------------------#
mottainai:
  # Enable/Disable storage mount from host.
  enable_storage_from_host: false

  # Enable/Disable binding of the port 3000 to host.
  # If you use a different port just edit the mottainai-dashboard profile.
  enable_dashboard_host_binding: false

  # Enable HTTPS on dashboard
  enable_dashboard_ssl: true

  # Using arangodb configuration
  enable_arangodb_backend: false

  # Enable Nginx Frontend
  enable_nginx_frontend: true

  # Enable binding on host port
  enable_nginx_host_binding: false


#-------------------------------------------#
# Steam OS params
#-------------------------------------------#
steam_user_id: "1000"
steam_user_gid: "1004"

#-------------------------------------------#
# General params
#-------------------------------------------#
connection: "local"
ephemeral: true
default_ubuntu_image: "ubuntu/21.04"

