oracledb:
  # Enable/Disable storage mount from host.
  enable_storage_from_host: false

  # Path of the host to mount in the container.
  host_data_path: /data/CONTAINER_STORAGE/oracle_container

connection: "local"

