
#-------------------------------------------#
# Oracle Database project customization
#-------------------------------------------#
oracledb:
  # Enable/Disable storage mount from host.
  enable_storage_from_host: false

  # Path of the host to mount in the container.
  host_data_path: /data/CONTAINER_STORAGE/oracle_container

#-------------------------------------------#
# Mottainai Service project customization
#-------------------------------------------#
mottainai:
  # Enable/Disable storage mount from host.
  enable_storage_from_host: false

  # Enable/Disable binding of the port 3000 to host.
  # If you use a different port just edit the mottainai-dashboard profile.
  enable_dashboard_host_binding: false

  # Enable HTTPS on dashboard
  enable_dashboard_ssl: true

  # Using arangodb configuration
  enable_arangodb_backend: true

  # Enable Nginx Frontend
  enable_nginx_frontend: true

  # Enable binding on host port
  enable_nginx_host_binding: true

  # Enable integration with lenencrypt
  enable_nginx_lenencrypt: false

  # Using privileged containers for services
  privileged_containers: true

  # Mottainai agent directory with
  # clients cert tree.
  # By default using the project directory.
  # If the path is relative then is based
  # on envs/mottainai-agent directory.
  #  agent_lxd_local_dir: "../lxd-conf/"
  agent_lxd_local_dir: "/tmp/lxd-conf"

  # Mottainai token to use with nginx reverse proxy.
  # This is needed until Mottainai will support public namespace.
  token: "XXXXXXXX"

  # Define the list of the public namespace to configure
  # in the nginx reverse proxy.
  public_namespaces:
    - namespace1

luet:
  enable_xfs_storage: true
  xfs_host_path: "/docker-xfs/"

#-------------------------------------------#
# MongoDB customization
#-------------------------------------------#
mongo:
  replicaset_nodes: 3

#-------------------------------------------#
# Steam OS params
#-------------------------------------------#
steam_user_id: "1000"
steam_user_gid: "1004"

#-------------------------------------------#
# General params
#-------------------------------------------#
connection: "local"
ephemeral: true
default_ubuntu_image: "ubuntu/21.04"
default_ubuntu_lts_image: "ubuntu/18.04"

