# This hook permit to create entries
# in the file /etc/hosts
# based on the variable <node_name>_hosts.
hooks:
- event: post-node-creation
  flags:
    - setup
  commands:
    - >-
      if [ -n "$DEBUG" ] ; then set -x ; fi ;
      node_hosts_options="$(echo ${node} | jq .name -r)_hosts" &&
      eval rows="\$$node_hosts_options" &&
      for r in $(echo $rows | jq .[] -c) ; do
      ip=$(echo $r | jq .ip -r) ;
      domain=$(echo $r | jq .domain -r | sed -e 's|,| |g') ;
      present=$(cat /etc/hosts | grep "${domain}" | wc -l) ;
      if [ "${present}" = "0" ] ; then
      echo "[/etc/hosts] Creating row: ${ip} ${domain}" ;
      echo "${ip} ${domain}" >> /etc/hosts ;
      fi ;
      done
